_BASE_: "./Base_Human36M.yaml"
EXPERIMENT_NAME: 'Baseline1'
WORKERS: 64
GPUS: (0,1,2)
OUTPUT_DIR: '/mancheng/result/PredPose/output/Human36M/PredPose/'


CORE_FUNCTION: CommonFunction

MODEL:
  NAME: PredPose_flow

  USE_PRF: true
  PRF_BASICBLOCK_NUM: 2
  PRF_INNER_CH: 34

  USE_PTM: true
  PTM_BASICBLOCK_NUM: 1
  PTM_INNER_CH: 17

  USE_PCN: true
  PRF_PTM_COMBINE_BASICBLOCK_NUM: 2
  PRF_PTM_COMBINE_INNER_CH: 17

  DEFORMABLE_CONV:
    DILATION:
      - 3
      - 6
      - 9
      - 12
      - 15
    AGGREGATION_TYPE: weighted_sum
LOSS:
  USE_TARGET_WEIGHT: true

TRAIN:
  AUTO_RESUME: true
  SAVE_MODEL_PER_EPOCH: 1
  BATCH_SIZE_PER_GPU: 8

VAL:
  BATCH_SIZE_PER_GPU: 8
  MODEL_FILE: ''
TEST:
  BATCH_SIZE_PER_GPU: 8
  MODEL_FILE: ''

DEBUG:
  VIS_SKELETON: false
  VIS_BBOX: false
